# Generated by Django 5.0.2 on 2024-07-01 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teknisyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('telefon', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Alet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('marka', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('durum', models.CharField(choices=[('bakimda', 'Bakımda'), ('teknisyende', 'Teknisyende'), ('rafta', 'Rafta')], default='rafta', max_length=20)),
                ('raf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servis.raf')),
                ('teknisyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servis.teknisyen')),
            ],
        ),
        migrations.CreateModel(
            name='AletHareketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alinma_zamani', models.DateTimeField(auto_now_add=True)),
                ('teslim_zamani', models.DateTimeField(blank=True, null=True)),
                ('alet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servis.alet')),
                ('teknisyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servis.teknisyen')),
            ],
        ),
    ]
